Port testing to Python 3
tahoe-lafs/tahoe-lafs pull request #990
Opened 2021-02-28 17:22 UTC by chadwhitacre

https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3621

2021-03-01 15:14 UTC, itamarst commented
Is this still WIP?

2021-03-08 00:04 UTC, chadwhitacre commented
Nope. Needed a CI cleanse. Should be good now, will merge next time I'm here unless someone objects.

2021-03-09 15:00 UTC, itamarst requested changes
1. You need to add this to `_python3.py`.
2. You haven't ported `allmydata.test.test_testing`.

2021-03-13 14:00 UTC, chadwhitacre commented
Thanks @itamarst, should be in a better spot now.

2021-03-15 14:27 UTC, itamarst approved these changes

2021-03-15 14:27 UTC, itamarst commented on src/allmydata/util/_python3.py
> +    "allmydata.testing",
This should probably be `allmydata.testing.web`.

2021-03-16 23:15 UTC, exarkun approved these changes
Apart from itamar's comment on the new entry in the ported-modules list (which I agree with), this looks good to me.  Please address that and then merge.

2021-03-17 20:05 UTC, merged